<?php

namespace Tests\Unit;

use App\Events\SessionCreated;
use App\Models\Group;
use App\Models\GroupSession;
use App\Models\Member;
use App\Models\Session;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class GroupSessionsTest extends TestCase
{
    use RefreshDatabase;

    protected Group $group;
    protected Session $session;
    protected GroupSession $groupSession;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Event::fake(SessionCreated::class);

        $this->group = factory(Group::class)->create(['user_id' => factory(User::class)->create()]);
        $this->session = factory(Session::class)->create(['group_id' => $this->group->id]);

        $this->groupSession = GroupSession::query()->create([
           'group_id' => $this->group->id,
           'session_id' => $this->session->id,
           'date' => Carbon::today(),
        ]);
    }

    /** @test */
    public function it_has_a_group()
    {
        $this->assertInstanceOf(Group::class, $this->groupSession->group);
        $this->assertTrue($this->group->is($this->groupSession->group));
    }

    /** @test */
    public function it_has_a_session()
    {
        $this->assertInstanceOf(Session::class, $this->groupSession->session);
        $this->assertTrue($this->session->is($this->groupSession->session));
    }

    /** @test */
    public function it_can_check_the_capacity()
    {
        $this->session->update(['capacity' => 1]);

        $this->assertTrue($this->groupSession->hasAvailableSlots());

        $this->groupSession->addMember(factory(Member::class)->raw());

        $this->assertFalse($this->groupSession->fresh()->hasAvailableSlots());
    }

    /** @test */
    public function it_can_add_members()
    {
        $this->assertEmpty($this->groupSession->members);

        $this->groupSession->addMember(factory(Member::class)->raw());

        $this->assertNotEmpty($this->groupSession->fresh()->members);
    }

    /** @test */
    public function it_errors_when_attempting_to_add_members_when_the_capacity_is_full()
    {
        $this->session->update(['capacity' => 1]);

        $this->groupSession->addMember(factory(Member::class)->raw());

        $this->expectException(\Exception::class);
        $this->expectExceptionMessage('No slots available in this session');

        $this->groupSession->fresh()->addMember(factory(Member::class)->raw());
    }
}
